### PR TITLE
Add @codec directive when decoding PB mdag instead of trying to detect it

### PR DESCRIPTION
**Pull request by mildred**
Remove obsolete IsOldProtobufNode() function that tried to tell if the IPLD
node was indeed an old protocol buffer format. Instead, rely on the @codec
directive for that. The @codec directive is automatically added when
decoding protocol buffers.

Obsoletes PR #12

### CODE REVIEW

**Comment by jbenet** [comment]
this is a good idea to me. the one place it fails is if people have been using the raw json representation of the current pb based objects, and try that. like for example:

``` sh
ipfs object get --enc=json <hash>  >obj
# update to new ipld
ipfs object put --enc=json <obj # breaks
```

i'm not sure how much people are using the json reps elsewhere... it may be ok to have to keep the `isOldProtobufNode` for those cases. so maybe: first check the `@codec`, then try `isOldProtobufNode` ?

**Comment by mildred** [comment]
This `--enc=json` option is not compatible with IPLD. Perhaps it should be made compatible to, but this is not currently the case. So adding `@codec` shouldn't change anything, it will break your use case.

I think we should't strive for JSON compatibility. We might want to provide a migration tool, but I don't see going further for the JSON serialization of protobuf messages.

In IPLD, we have a JSON message that looks like this:

```
{
  "@attrs": {
    "links": [ <all the links here> ],
    "data": "<the data here>",
  },
  "foo": <link named "foo">,
  "bar": <link named "bar">,
}
```

See Issue #9 and PR #11

What `ipfs object get --enc=json` returns is something like:

```
{
  "Links": [ ... ],
  "Data": "...",
}
```

Which is completely different and is currently not understood by IPLD.

**Comment by jbenet** [comment]
> This --enc=json option is not compatible with IPLD. 

i dont understand this point. im probably missing something obvious.

> What ipfs object get --enc=json returns is something like:

right, i wanted `isOldProtobufNode` to be there to run over a document like that and thus understand it was an old protobuf structure. it is very characteristic and can be recognized easily. i agree it's not clean, but i do not want to break any links or data lying around that people use.

(i.e. i'd be OK giving up "json-rep of an old protobuf mdag node" but i'm not yet convinced that we have to, and it would be nice + important for users to support it)

**Comment by jbenet** [comment]
so basically, it would check the document, if it matches, convert it to the new representation, and so on.

**Comment by mildred** [comment]
I'm not convinced it should be implemented in go-ipld. I'd rather see this code in the implementation of the `object put --enc=json` code. At the limit, go-ipld could provide a function to do the conversion. But the decision to convert should go to the `object put` command depending on the `--enc` option.

**Comment by jbenet** [comment]
well no, the `object put` command may never be involved-- this could be direct programmatic use. there's a bunch of tools that use ipfs directly from Go.

what i mean is that whenever go-ipld parses a JSON document in the _expected_ structure of protobuf v1:

``` json
{
  "Links": [ 
    { "Name": "liinkname", "Hash": "Qm...", "Size": 1234 } 
  ],
  "Data": "...",
}
```

to convert it using what we know of protobuf v1, into:

``` json
{
  "@attrs": {
    "Links": [ 
      { "Name": "liinkname", "Hash": "Qm...", "Size": 1234 } 
    ],
    "Data": "...",
  },
  "liinkname": { "mlink": "Qm...", "size": 1234 },
}
```

btw, not sure if size would break current impl atm. would be useful to allow other keys in that map.

**Comment by mildred** [comment]
What I don't like about this, is that we have `ld2json(json2ld(JSON)) != JSON` when `JSON` is

```
{
  "Links": [ 
    { "Name": "liinkname", "Hash": "Qm...", "Size": 1234 } 
  ],
  "Data": "...",
}
```

At the minimum I'd like to introduce a boolean in the API to perform the conversion because we expect legacy JSON, or not to convert because we know there is no legacy JSON around. This will break the Go function signature, and consumers of that API will need to decide if the JSON is possibly legacy or not.

This will allow `ipfs object put` to have an option `--no-legacy` for example.

**Comment by jbenet** [comment]
Hmmm makes sense. not yet sure. i'm usually :-1: on breaking interfaces, but warning users is useful. 

if we decide not to break the interface, can always have another function call and clearly label it to users to use that one instead to achieve different behavior.

> This will allow ipfs object put to have an option --no-legacy for example.

:+1: on having an option, bit :-1: on that name, as it's not guaranteed that IPLD itself wont become legacy in the future. not sure on a good name.

Hmmmm all this is tricky. 

It may be _sane_ to just say that _that_ structure is just the protobuf structure forever. can you really see a json doc like that the user would want that IS NOT ipfs protobuf json? i mean, it would have to parse right (exact structure, links would be hashes of base58, etc).

**Comment by mildred** [comment]
> :+1: on having an option, bit :-1: on that name, as it's not guaranteed that IPLD itself wont become legacy in the future. not sure on a good name.

I was more thinking to myself `--enc=json/mdagv1` or `--enc=json/ipld`. But that's a front-end issue.

> It may be sane to just say that that structure is just the protobuf structure forever. can you really see a json doc like that the user would want that IS NOT ipfs protobuf json? i mean, it would have to parse right (exact structure, links would be hashes of base58, etc).

Why not. Just add a new item in the message that would contain IPLD. Messages that contain links + optional data will be decoded as before. Messages with just IPLD will get decoded as IPLD. We shouldn't allow of course mixing the two.

But that's throwing away the purpose of multicodec as this will be handled by protocol buffers instead. We can always make use of it, but on top of protocol buffers. Not very beautiful.

---

Assuming we keep IPLD this way, to move forward on this issue, I suggest the following functions in `ipld/codec`:

```
// Return a multicodec that decodes a data structure in the
// protocol buffer format as returned by `ipfs object get`
func MulticodecProtobuf() mc.Multicodec

// Return a multicodec that decodes a data structure in the
// IPLD format only
func MulticodecIPLD() mc.Multicodec

// Return a multicodec that decodes a data structure in the
// protocol buffer format if it can. Else it decdes the data
// structure in IPLD format
func MulticodecAuto() mc.Multicodec
```

We can reduce the number of functions and add boolean / enum parameters as we want, but the three basic functions are these I believe.

**Comment by jbenet** [comment]
> But that's throwing away the purpose of multicodec as this will be handled by protocol buffers instead. We can always make use of it, but on top of protocol buffers. Not very beautiful.

indeed. 

well not by protocol buffers only, as parsing of the `json/mdagv1` representation will need to handle this (before being serialized to `protobuf/mdagv1`). the stored protobufs can be prefixed by us appropriately. it's some in flight/stored elsewhere that are the problem.

maybe you're right about breaking the interface, but eventually. as in, down the road we could see if `json/mdagv1` is even a format people use much, and if not, transition to not accepting (i.e. asking people to convert it to feed it in as protobuf instead, and provide conversion tools or whatever). this would help drive stragglers to move over to IPLD.

---

> Assuming we keep IPLD this way, to move forward on this issue, I suggest the following functions in

yep, i like those! and that way users can chose. we can use auto for most places and expose the others with flags as needed. and we can maybe have a map with their multicodec code to can be specified in cli by multicodec code. 

And maybe we can put:

``` go
func MulticodecProtobuf() mc.Multicodec
```

inside of an `mdag1` package inside of this repo --  so that it's clear when importing where it comes from.

also, maybe `ProtobufMulticodec` sounds better?  (or maybe even `ProtobufMDag1Multicodec` --- oof javaness!)

**Comment by mildred** [comment]
As discussed in ipfs/specs#63, we are not going to use `@codec` for the moment.

**Pull request closed without merging**
