### PR TITLE
repurpuse this repo as the go-ipld entry point

### PR DESCRIPTION
**Pull request by daviddias**

### CODE REVIEW

**Comment by Stebalien** [comment]
Can we rename and then recreate this repo? I agree that we should do this (the plan is to make something like go-libp2p) but we probably don't want to keep the history.

**Comment by daviddias** [comment]
In the past people always preferred to keep history when these types of changes happened. Good to merge and move forward?

**Comment by Stebalien** [comment]
Maybe... My concern is that this isn't really a part of the history of this repo. I'd like to keep it, I'm just not convinced we should keep it *here*.

**Comment by daviddias** [comment]
I'll create a new repo then :)

**Pull request closed without merging**
